### ISSUE TITLE
Interface to define vocabulary

### ISSUE THREAD

**Issue by vibby** [AdventistCommons/adventistcommons.org#137]
In editor, some words can be described. But we do not have a place to define the words and description. I will do it in the admin.

**Comment by vibby** [comment]
Admin is now here : http://develop.adventistcommons.org/admin/index.html

**Comment by m-dotcom** [comment]
Where can I see this definitions in the editor? Maybe I am not understanding correctly.

**Comment by vibby** [comment]
@m-dotcom, Admin is here : [http://develop.adventistcommons.org/admin/index.html#/login](http://develop.adventistcommons.org/admin/index.html#/login) You must log with a user that is admin.
Then you should enter the admin. There is a menu on the left, the items that do not work at the moment are Users, Projects and Products but other should just work. For every type, it is a simple crud : Create/Read/Update/Delete.
So in the part «definitions», you can set a new word that you want to be defined in the editor (original text area).

**Comment by m-dotcom** [comment]
I deleted the complete URL of your comment above because I don't want people to access that site yet while we are working. 

As far as the admin areas is concerned, I logged in as admin but get the below screen for all menu items. 

<img width="688" alt="Screen Shot 2020-03-26 at 7 39 29 AM" src="https://user-images.githubusercontent.com/51795720/77614081-fe151b00-6f34-11ea-925d-18d4fa6fe309.png">

**Comment by vibby** [comment]
I saw that bug. I didn’t fix it but I found a way to avoid it : just reload the page.
Sometimes, it happens because authentication has been lost. So you can also try the logout but button and login once more.

**Comment by m-dotcom** [comment]
Ok, I saw this now and understand what you mean. I think this "Definition" section needs to be different... 

Every person who is approved to review a language should be able to see this in his account setting page. The purpose of this is that he can define how a specific word should be translated into the language that he is approved off. For example, the word "Seventh-day Adventists" is often translated differently in some languages and we need to suggest to users who translate and come access it how it should be translated.

Since language reviewers are experienced translators, they should be in charge of this. I hope this makes sense, if not, let me know and I will try to explain it again.

**Comment by vibby** [comment]
Ok @m-dotcom I think I got it.
So a reviewer in any language could be able to add / edit them all ?
Can I ask you a design of that interface ?

**Comment by m-dotcom** [comment]
Yes, you are right about reviewer. I added a card in Trello and will work on a design. 
This feature is not needed right now and not high priority.
