### ISSUE TITLE
Definition system conflict

### ISSUE THREAD

**Issue by vibby** [AdventistCommons/adventistcommons.org#143]
I don’t if you aware of it @m-dotcom, in the frontend that was done : there is a system that gives definition of words when user double click on it. Definition comes from webservice https://wordsapiv1.p.rapidapi.com
The problem is that : it is not compatible with the action to give focus to translation area when selecting a sentence.

To give you a better understanding of what is happening :
- A user double-click on a word in the original text area
- The selected word is taken to give its definition in a small box

But, for a better user experience I added this action between the two (it happens on first click) :
- The focus (cursor) is given to the translation textarea so user can give a translation without clicking it. This action remove the selection so definition mechanism do not work anymore.

What do you think is the most important : facilitate translation work or ability to give definition of words ?

**Comment by m-dotcom** [comment]
I tried to double click on a word right now but it seems that this features is not activated yet. I think most important will be to facilitate the translation work. Dictionary will be helpful, but I think more important is the Machine Translation first because I know it can help greatly. I would suggest to wait with the dictionary for now and later see how we can implement it, what do you think?

**Comment by vibby** [comment]
This is normal it does not work, because focus goes to translation textarea as I said.
Will see that later.
Regards
